const INSTRUCTIONS_CONSTANTS = [
  {
    header: "Fill in Your Details",
    desc: "Enter your first name, last name, phone number, and email address.",
  },
  {
    header: "Select a Date & Time",
    desc: "Choose your preferred appointment schedule.",
  },
  {
    header: "Add Additional Notes (optional)",
    desc: " Specify any concerns or special requests.",
  },
  {
    header: "Choose a Service",
    desc: "Select at least one service that suits your needs.",
  },

  {
    header: "Submit & Review Your Form",
    desc: " Click the submit to complete your appointment request.",
  },
  {
    header: "Wait for Confirmation",
    desc: "You will receive an email at the email address you provided regarding the status of your appointment.",
  },
];

export default INSTRUCTIONS_CONSTANTS;
