const SERVICES_CONSTANTS = [
  "Psychological & Psychiatric Testing/Assessments",
  "Assessment and Therapy for Children with Special Needs and Concerns",
  "Clinical Consultation, Counseling, Psycho-social Interventions, and Referrals",
  "Tutorial and Review Classes for PRC Board Examinations",
  "Program Development and Administration for Students, Employees, and Organizations",
  "Trainings, Seminars, Workshops, Recollection, and Team Building Organizing and Facilitating",
];

export default SERVICES_CONSTANTS;
