const SERVICES_OFFERED = [
  {
    category: "Psychological & Psychiatric Testing/Assessments",
    details: [
      "Employment/Industrial purposes",
      "Internship/OJT purposes",
      "Criminal/civil court cases",
      "Diagnostic/Clinical purposes",
      "Academic and research purposes",
    ],
  },
  {
    category:
      "Assessment and Therapy for Children with Special Needs and Concerns",
    details: [
      "Behavioral Concerns (e.g., Conduct Disorder, ADHD, etc.)",
      "Developmental Concerns (ASD, GDD, etc.)",
      "Intellectual Ability Assessment",
      "Emotional Quotient Assessment",
      "Other special concerns of children and adolescents",
    ],
  },
  {
    category:
      "Clinical Consultation, Counseling, Psycho-social Interventions, and Referrals",
    details: [
      "Interpersonal and interpersonal concerns",
      "Marital and parenting concerns",
      "Trauma assessment and management",
      "Other special concerns",
    ],
  },
  {
    category: "Tutorial and Review Classes for PRC Board Examinations",
    details: [
      "Guidance and Counseling",
      "Psychology/Psychometrician",
      "Education",
    ],
  },
  {
    category:
      "Program Development and Administration for Students, Employees, and Organizations",
    details: [],
  },
  {
    category:
      "Trainings, Seminars, Workshops, Recollection, and Team Building Organizing and Facilitating",
    details: [],
  },
];

export default SERVICES_OFFERED;
