const TIME_CONSTANTS = [
  { name: "09:00 AM", value: "09:00 AM" },
  { name: "10:00 AM", value: "10:00 AM" },
  { name: "11:00 AM", value: "11:00 AM" },
  { name: "12:00 PM", value: "12:00 PM" },
  { name: "01:00 PM", value: "13:00 PM" },
  { name: "02:00 PM", value: "14:00 PM" },
  { name: "03:00 PM", value: "15:00 PM" },
  { name: "04:00 PM", value: "16:00 PM" },
];

export default TIME_CONSTANTS;
