export const DUMMY_APPOINTMENTS = [
  {
    firstname: "Juan",
    lastname: "Dela Cruz",
    phone: "09123456789",
    email: "juan.delacruz@example.com",
    date: new Date("2025-05-10"),
    time: "10:00 AM",
    branch: "Dagupan City",
    selectedServices: ["Therapy Session"],
    comments: "Looking forward to the session.",
    status: "pending",
  },
  {
    firstname: "Maria",
    lastname: "Santos",
    phone: "09234567890",
    email: "maria.santos@example.com",
    date: new Date("2025-05-11"),
    time: "2:00 PM",
    branch: "Vigan City",
    selectedServices: ["Consultation", "Counseling"],
    comments: "Need help with stress management.",
    status: "confirmed",
  },
  {
    firstname: "Pedro",
    lastname: "Garcia",
    phone: "09345678901",
    email: "pedro.garcia@example.com",
    date: new Date("2025-05-12"),
    time: "4:30 PM",
    branch: "Urdaneta City",
    selectedServices: ["Mental Health Screening"],
    comments: "Referred by a friend.",
    status: "canceled",
  },
  {
    firstname: "Anna",
    lastname: "Reyes",
    phone: "09456789012",
    email: "anna.reyes@example.com",
    date: new Date("2025-05-13"),
    time: "11:00 AM",
    branch: "Mangaldan",
    selectedServices: ["Psychological Assessment"],
    comments: "Curious about psychological assessment.",
    status: "pending",
  },
  {
    firstname: "Carlos",
    lastname: "Lopez",
    phone: "09567890123",
    email: "carlos.lopez@example.com",
    date: new Date("2025-05-14"),
    time: "3:15 PM",
    branch: "Dagupan City",
    selectedServices: ["Family Counseling"],
    comments: "Would like to discuss family matters.",
    status: "completed",
  },
  {
    firstname: "Luis",
    lastname: "Mendoza",
    phone: "09678901234",
    email: "luis.mendoza@example.com",
    date: new Date("2025-05-15"),
    time: "9:00 AM",
    branch: "Vigan City",
    selectedServices: ["Consultation"],
    comments: "General check-up.",
    status: "confirmed",
  },
  {
    firstname: "Elena",
    lastname: "Rodriguez",
    phone: "09789012345",
    email: "elena.rodriguez@example.com",
    date: new Date("2025-05-16"),
    time: "1:30 PM",
    branch: "Urdaneta City",
    selectedServices: ["Therapy Session"],
    comments: "Dealing with anxiety.",
    status: "pending",
  },
  {
    firstname: "Samuel",
    lastname: "Fernandez",
    phone: "09890123456",
    email: "samuel.fernandez@example.com",
    date: new Date("2025-05-17"),
    time: "3:00 PM",
    branch: "Mangaldan",
    selectedServices: ["Counseling"],
    comments: "Relationship issues.",
    status: "canceled",
  },
  {
    firstname: "Beatrice",
    lastname: "Villanueva",
    phone: "09901234567",
    email: "beatrice.villanueva@example.com",
    date: new Date("2025-05-18"),
    time: "10:45 AM",
    branch: "Dagupan City",
    selectedServices: ["Mental Health Screening"],
    comments: "Routine check-up.",
    status: "pending",
  },
  {
    firstname: "Fernando",
    lastname: "Castro",
    phone: "09112223344",
    email: "fernando.castro@example.com",
    date: new Date("2025-05-19"),
    time: "4:15 PM",
    branch: "Vigan City",
    selectedServices: ["Psychological Assessment"],
    comments: "Need a formal assessment for work.",
    status: "confirmed",
  },
  {
    firstname: "Cecilia",
    lastname: "Navarro",
    phone: "09223334455",
    email: "cecilia.navarro@example.com",
    date: new Date("2025-05-20"),
    time: "8:30 AM",
    branch: "Urdaneta City",
    selectedServices: ["Consultation"],
    comments: "Work-related stress.",
    status: "pending",
  },
  {
    firstname: "Daniel",
    lastname: "Ortiz",
    phone: "09334445566",
    email: "daniel.ortiz@example.com",
    date: new Date("2025-05-21"),
    time: "5:00 PM",
    branch: "Mangaldan",
    selectedServices: ["Therapy Session"],
    comments: "Anxiety issues.",
    status: "completed",
  },
  {
    firstname: "Isabel",
    lastname: "Cruz",
    phone: "09445556677",
    email: "isabel.cruz@example.com",
    date: new Date("2025-05-22"),
    time: "9:45 AM",
    branch: "Dagupan City",
    selectedServices: ["Counseling"],
    comments: "Grief counseling.",
    status: "pending",
  },
  {
    firstname: "Ricardo",
    lastname: "Morales",
    phone: "09556667788",
    email: "ricardo.morales@example.com",
    date: new Date("2025-05-23"),
    time: "12:15 PM",
    branch: "Vigan City",
    selectedServices: ["Mental Health Screening"],
    comments: "Annual mental check.",
    status: "confirmed",
  },
  {
    firstname: "Angela",
    lastname: "Bautista",
    phone: "09667778899",
    email: "angela.bautista@example.com",
    date: new Date("2025-05-24"),
    time: "2:45 PM",
    branch: "Urdaneta City",
    selectedServices: ["Family Counseling"],
    comments: "Family communication issues.",
    status: "pending",
  },
  {
    firstname: "Miguel",
    lastname: "Torres",
    phone: "09778889900",
    email: "miguel.torres@example.com",
    date: new Date("2025-05-25"),
    time: "6:00 PM",
    branch: "Mangaldan",
    selectedServices: ["Psychological Assessment"],
    comments: "Career assessment.",
    status: "completed",
  },
  {
    firstname: "Sophia",
    lastname: "Gutierrez",
    phone: "09889990011",
    email: "sophia.gutierrez@example.com",
    date: new Date("2025-05-26"),
    time: "11:15 AM",
    branch: "Dagupan City",
    selectedServices: ["Consultation"],
    comments: "General stress relief.",
    status: "pending",
  },
  {
    firstname: "Emilio",
    lastname: "Castillo",
    phone: "09990001122",
    email: "emilio.castillo@example.com",
    date: new Date("2025-05-27"),
    time: "3:30 PM",
    branch: "Vigan City",
    selectedServices: ["Therapy Session"],
    comments: "Depression management.",
    status: "confirmed",
  },
  {
    firstname: "Valeria",
    lastname: "Ramos",
    phone: "09101112233",
    email: "valeria.ramos@example.com",
    date: new Date("2025-05-28"),
    time: "7:00 PM",
    branch: "Urdaneta City",
    selectedServices: ["Counseling"],
    comments: "Work-life balance.",
    status: "pending",
  },
];
