export const DUMMY_ADMINS = [
  {
    firstname: "Juan",
    middlename: "Dela",
    lastname: "Cruz",
    email: "juan.cruz@example.com",
    phone: "+639123456789",
    password: "securePass123",
    role: "admin",
    profilePic:
      "https://res.cloudinary.com/demo/image/upload/v1610000000/juan_cruz.jpg",
    status: "active",
    branch: "Dagupan City",
  },
  {
    firstname: "Maria",
    middlename: "Santos",
    lastname: "Reyes",
    email: "maria.reyes@example.com",
    phone: "09123456789",
    password: "strongPass456",
    role: "super_admin",
    profilePic:
      "https://res.cloudinary.com/demo/image/upload/v1610000000/maria_reyes.jpg",
    status: "inactive",
    branch: "Urdaneta City",
  },
  {
    firstname: "Carlos",
    middlename: "Garcia",
    lastname: "Lopez",
    email: "carlos.lopez@example.com",
    phone: "+639876543210",
    password: "randomPass789",
    role: "admin",
    profilePic: "",
    status: "active",
    branch: "Mangaldan",
  },
  {
    firstname: "Anna",
    middlename: "Victoria",
    lastname: "Lim",
    email: "anna.lim@example.com",
    phone: "09112223344",
    password: "annaPass123",
    role: "admin",
    profilePic: "",
    status: "inactive",
    branch: "Vigan City",
  },
  {
    firstname: "Michael",
    middlename: "Joseph",
    lastname: "Tan",
    email: "michael.tan@example.com",
    phone: "+639554433221",
    password: "michaelTan456",
    role: "super_admin",
    profilePic:
      "https://res.cloudinary.com/demo/image/upload/v1610000000/michael_tan.jpg",
    status: "active",
    branch: "Dagupan City",
  },
  {
    firstname: "Jessica",
    middlename: "Anne",
    lastname: "Torres",
    email: "jessica.torres@example.com",
    phone: "09223334455",
    password: "jessicaTorres789",
    role: "admin",
    profilePic: "",
    status: "inactive",
    branch: "Urdaneta City",
  },
  {
    firstname: "David",
    middlename: "Francisco",
    lastname: "Ramos",
    email: "david.ramos@example.com",
    phone: "+639667788990",
    password: "davidRamos101",
    role: "admin",
    profilePic:
      "https://res.cloudinary.com/demo/image/upload/v1610000000/david_ramos.jpg",
    status: "active",
    branch: "Mangaldan",
  },
  {
    firstname: "Christine",
    middlename: "Mae",
    lastname: "Dizon",
    email: "christine.dizon@example.com",
    phone: "09178889900",
    password: "christineDizon202",
    role: "super_admin",
    profilePic: "",
    status: "active",
    branch: "Vigan City",
  },
  {
    firstname: "Daniel",
    middlename: "Bryan",
    lastname: "Fernandez",
    email: "daniel.fernandez@example.com",
    phone: "+639812345678",
    password: "danielFernandez303",
    role: "admin",
    profilePic: "",
    status: "inactive",
    branch: "Dagupan City",
  },
  {
    firstname: "Karen",
    middlename: "Louise",
    lastname: "Santiago",
    email: "karen.santiago@example.com",
    phone: "09193456789",
    password: "karenSantiago404",
    role: "super_admin",
    profilePic:
      "https://res.cloudinary.com/demo/image/upload/v1610000000/karen_santiago.jpg",
    status: "active",
    branch: "Urdaneta City",
  },
];
